### ISSUE TITLE
Rename all instances of "matches" to "isNotMobile"

### ISSUE THREAD

**Issue by dotcomstar** [dotcomstar/Triviale#202]

**Comment by withoutwax13** [comment]
Hi @dotcomstar, can I work on this ticket? Thanks!

**Comment by dotcomstar** [comment]
Awesome, thanks for the help! I just accepted your PR. I'm just curious, how did you find this repository? Was it because I tagged the issue as good first issue?

**Comment by withoutwax13** [comment]
Yes @dotcomstar, it is because of the for good first issue label.
